import '../styles/globals.css'
import "../utils/typing"

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ Component, pageProps }) {
    return (
        <div>
            <Component {...pageProps} />
        </div>
    )
}
